# Generated by Django 5.1.2 on 2024-11-29 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
