# Generated by Django 5.1.2 on 2024-11-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmts', '0003_maintenanceticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
